ARG VERSION=v3.2.1
FROM prom/prometheus:${VERSION}

# Switch to root to change permissions/ownership if needed
USER root

# Copy the config and entrypoint
COPY prom.yml /etc/prometheus/prom.yml
COPY entrypoint.sh /bin/entrypoint.sh

# Make the entrypoint executable
RUN chmod +x /bin/entrypoint.sh

# Switch back to the 'nobody' user (standard for Prometheus security)
USER nobody

# Override the default Entrypoint to run our script
ENTRYPOINT ["/bin/entrypoint.sh"]